version: '2'
services:
        vid-server:
                image: onap/vid
                ports:
                - "8080:8080"
                links:
                - vid-mariadb:vid-mariadb-docker-instance
                environment:
                - JVM_OPTS=-Xmx1536m -Xms1536m
        vid-mariadb:
                image: mariadb:10.1.11
                ports:
                - "3306:3306"
                volumes:
                - /var/lib/mysql
